### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by BatyaMedic** [warhawk3407/bgpanelv2#11]
SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1 in /var/www/html/bgpanelv2/install/sql/full.php on line 549
Panel can be installed in this time?

**Comment by Owned67** [comment]
No

**Comment by warhawk3407** [comment]
Fixed this issue with this commit: https://github.com/warhawk3407/bgpanelv2/commit/379d8819f631dd506187e24bdab05c63584cab65

The panel is in very early development stage, so you may have errors like this. I'm working on the core panel at the moment, features will come with time.
You can try to install the panel to see the new GUI or how the V2 is built.

I close this issue, solved.
