### ISSUE TITLE
Bad route : login/process (404 Not Found)

### ISSUE THREAD

**Issue by BatyaMedic** [warhawk3407/bgpanelv2#12]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /bgpanelv2-master/login/process was not found on this server.</p> <hr> <address>Apache/2.4.7 (Ubuntu) Server at 192.168.1.40 Port 80</address> </body></html>

Where`s login folder?

**Comment by warhawk3407** [comment]
It is a virtual path in fact.

Strange error, could you detail your web server environment and configuration ?

Download the very very last build at this hour : https://github.com/warhawk3407/bgpanelv2/archive/master.zip

**Comment by warhawk3407** [comment]
Ok some points of interest in order to solve the problem :
- are you using apache2 as your web server ? (it is a requirement)
- have you uploaded correctly on your server the .htaccess in the "main directory bgpanelv2-master" ?
(https://github.com/warhawk3407/bgpanelv2/blob/master/.htaccess)

**Comment by BatyaMedic** [comment]
Im using apache2.
All is working now.

**Comment by warhawk3407** [comment]
ok, good to know. Remember, it is a WIP.
