### ISSUE TITLE
Unable to find .htaccess file

### ISSUE THREAD

**Issue by SphinxTwo** [warhawk3407/bgpanelv2#16]
Trying to get the install working for v2, there is a slight problem.
"Unable to find .htaccess.

 

Make sure you have uploaded the ".htaccess" file at the root of the application directory then retry."

However, it is clearly there in the application directory; /var/www/bgp2/.htaccess
Accessing 192.168.1.22:81/bgp2/.htaccess is forbidden. Running Apache on Centos 7.
http://i.theforgivenbeast.tk/1444502565.png

**Comment by djoe45** [comment]
Copy paste on install folder.

**Comment by SphinxTwo** [comment]
Okay thank you. Now I have an SSH and RSA write permission problem. Where is the location of the folder/file?
