### ISSUE TITLE
Checking for SSH and RSA keys directory write permission

### ISSUE THREAD

**Issue by fabiango86** [warhawk3407/bgpanelv2#17]
When I wan't to install I get Checking for SSH and RSA keys directory write permission  failed

how can i fix this?

**Comment by MrPalamen** [comment]
/install/index.php
line 713 
if (is_writable( RSA_KEYS_DIR ) && is_writable( SSH_KEYS_DIR ))
a
if (is_writable( RSA_KEYS_DIR ))

**Comment by warhawk3407** [comment]
Yes.

Note : You can't do anything with this current version of BGPanel V2. In fact, you can only see how the future pseudo-framework will work, that's all. For an enduser, it is useless until the release.
