### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by DropMotion** [warhawk3407/bgpanelv2#18]
## Hi
I can't install the BGpanelV2 i got this error:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dropmoti_bgp.bgp_config' doesn't exist in /home/dropmotionninja/public_html/gpanel/init.app.php on line 198
}
```

**Comment by warhawk3407** [comment]
Updated the installer ~ may fix this error. This current experimental version will not provide support until official release / announcement.

Note : You can't do anything with this current version of BGPanel V2. In fact, you can only see how the future pseudo-framework will work, that's all. For an enduser, it is useless until the release.
