### ISSUE TITLE
cannot LOGIN

### ISSUE THREAD

**Issue by rajabilal555** [warhawk3407/bgpanelv2#19]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /svpanel2/login/process was not found on this server.</p> <hr> <address>Apache/2.2.22 (Debian) Server at cp.wgaming.net Port 80</address> </body></html> 

What I cannot even login.... ?

**Comment by rajabilal555** [comment]
Do i even have a LOGIn directory  ?

**Comment by warhawk3407** [comment]
mod_rewrite is mandatory. Updated the installer. You can't do anything with this current version og BGPanel V2. In fact, you can only see how the future pseudo-framework will work, that's all. For an enduser, it is useless until the release.
