### ISSUE TITLE
Says I Don't Have Apache2 During Install.

### ISSUE THREAD

**Issue by AutoJukebox** [warhawk3407/bgpanelv2#20]
So i was upgrading my panel to V2 and during the install requirement check it said i did not have Apache2 which is strange cause i do.

I'm currently use Plesk Web Panel for my Web Server with Apache2 V.2.4.7

**Comment by DarrenRainey** [comment]
You shouldn't be upgrading to this panel just yet as its still being developed and there will be allot of bugs until the whole thing is complete

**Comment by AutoJukebox** [comment]
I plan on rewriting a bunch of it to work for my needs, Guess I'll have to put a override for the requirements.
