### ISSUE TITLE
Login not working!

### ISSUE THREAD

**Issue by ghost** [warhawk3407/bgpanelv2#24]
Hey,

I successfully installed the panel, but once I try to login It says it's invalid.

Here are some screens:

Proof that it installed: http://www2.pic-upload.de/img/31883270/44e3e0a346527a4b98e4b86b9b01059d.png

Login Page: http://www2.pic-upload.de/img/31883272/96d04ff12c6ac2620ff4009f16000743.png

Thanks.

**Comment by tomgie** [comment]
Seems like there's an error near the top, https://gyazo.com/3a71b30c764f4f8ec2450f9cf3441ecd more than likely have to go through the default db and fix it there.

**Comment by systemroot** [comment]
your proof it's wrong. 
because for bgpanelv2 isn't "admin" default username but "root". 
so.

**Comment by Darksleep** [comment]
What systemroot said it not v2 that's 0.4.7 says all over the screen download and re-upload and try again make sure it says 2.?.? this time
