### ISSUE TITLE
Install Script Error PHP7.0

### ISSUE THREAD

**Issue by mclucario** [warhawk3407/bgpanelv2#25]
Hey, I'm currently using PHP 7.0 on Ubuntu 16.04 and when installing stuff with Apache2 I get this error:

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Math_BigInteger has a deprecated constructor in /var/www/bgp/app/libs/phpseclib/Math/BigInteger.php on line 176
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'last_activity' in /var/www/bgp/install/sql/full.php on line 467`

**Comment by Darksleep** [comment]
I don't think your going to get any help this project is deader then dead

**Comment by mclucario** [comment]
I see. Welp.

**Comment by DarrenRainey** [comment]
Well the original developer (warhawk3407) hasn't been active in a while so I think I might fork this and update it in the future

**Comment by warhawk3407** [comment]
I will try to be PHP 7.0 compliant as possible in the future
