### ISSUE TITLE
Error 404 /login after install

### ISSUE THREAD

**Issue by Paca** [warhawk3407/bgpanelv2#6]
Hello,

I was trying the last source to check this new version.
I have install the panel with success but i get a 404 on redirect route /login

**** 
192.168.1.161 - - [09/Jun/2015:21:16:28 +0200] "GET /bgpv2/login HTTP/1.1" 404 183 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"

****

What I am missing. Is there something related to .htaccess rewrite engin.

Thanks for your help.

**Comment by warhawk3407** [comment]
Hello Paca ! :-)

Well, as usual, sorry for this late support...

BGPanelV2 is still very unstable in its current state.

I will notify the world when it will be ready for beta testing.

Best Regards,
Nikita Rousseau
